USE [lab14node]
GO

/****** Object:  Table [dbo].[AUDITORIUM_TYPE]    Script Date: 12/24/2019 10:42:14 AM ******/
DROP TABLE [dbo].[AUDITORIUM_TYPE]
GO

/****** Object:  Table [dbo].[AUDITORIUM_TYPE]    Script Date: 12/24/2019 10:42:14 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AUDITORIUM_TYPE](
	[AUDITORIUM_TYPE] [nvarchar](50) NOT NULL,
	[AUDITORIUM_TYPENAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AUDITORIUM_TYPE] PRIMARY KEY CLUSTERED 
(
	[AUDITORIUM_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


