USE [lab14node]
GO

ALTER TABLE [dbo].[AUDITORIUM] DROP CONSTRAINT [FK_AUDITORIUM_AUDITORIUM_TYPE]
GO

/****** Object:  Table [dbo].[AUDITORIUM]    Script Date: 12/24/2019 10:40:22 AM ******/
DROP TABLE [dbo].[AUDITORIUM]
GO

/****** Object:  Table [dbo].[AUDITORIUM]    Script Date: 12/24/2019 10:40:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AUDITORIUM](
	[AUDITORIUM_ID] [nvarchar](50) NOT NULL,
	[AUDITORIUM_NAME] [nvarchar](50) NOT NULL,
	[AUDITORIUM_CAPACITY] [int] NOT NULL,
	[AUDITORIUM_TYPE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AUDITORIUM] PRIMARY KEY CLUSTERED 
(
	[AUDITORIUM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AUDITORIUM]  WITH CHECK ADD  CONSTRAINT [FK_AUDITORIUM_AUDITORIUM_TYPE] FOREIGN KEY([AUDITORIUM_TYPE])
REFERENCES [dbo].[AUDITORIUM_TYPE] ([AUDITORIUM_TYPE])
GO

ALTER TABLE [dbo].[AUDITORIUM] CHECK CONSTRAINT [FK_AUDITORIUM_AUDITORIUM_TYPE]
GO


