USE [lab14node]
GO

ALTER TABLE [dbo].[PULPIT] DROP CONSTRAINT [FK_PULPIT_FACULTY]
GO

/****** Object:  Table [dbo].[PULPIT]    Script Date: 12/24/2019 10:45:32 AM ******/
DROP TABLE [dbo].[PULPIT]
GO

/****** Object:  Table [dbo].[PULPIT]    Script Date: 12/24/2019 10:45:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PULPIT](
	[PULPIT_ID] [nvarchar](50) NOT NULL,
	[PULPIT_NAME] [nvarchar](50) NOT NULL,
	[FACULTY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PULPIT] PRIMARY KEY CLUSTERED 
(
	[PULPIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PULPIT]  WITH CHECK ADD  CONSTRAINT [FK_PULPIT_FACULTY] FOREIGN KEY([FACULTY])
REFERENCES [dbo].[FACULTY] ([FACULTY_ID])
GO

ALTER TABLE [dbo].[PULPIT] CHECK CONSTRAINT [FK_PULPIT_FACULTY]
GO


