USE [lab14node]
GO

ALTER TABLE [dbo].[TEACHER] DROP CONSTRAINT [FK_TEACHER_PULPIT]
GO

/****** Object:  Table [dbo].[TEACHER]    Script Date: 12/24/2019 10:48:18 AM ******/
DROP TABLE [dbo].[TEACHER]
GO

/****** Object:  Table [dbo].[TEACHER]    Script Date: 12/24/2019 10:48:18 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEACHER](
	[TEACHER_ID] [nvarchar](50) NOT NULL,
	[TEACHER_NAME] [nvarchar](50) NOT NULL,
	[PULPIT] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TEACHER] PRIMARY KEY CLUSTERED 
(
	[TEACHER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TEACHER]  WITH CHECK ADD  CONSTRAINT [FK_TEACHER_PULPIT] FOREIGN KEY([PULPIT])
REFERENCES [dbo].[PULPIT] ([PULPIT_ID])
GO

ALTER TABLE [dbo].[TEACHER] CHECK CONSTRAINT [FK_TEACHER_PULPIT]
GO


